package ingress

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// CaddyDriver generates Caddyfile blocks.
type CaddyDriver struct {
	configDir string
	reloadCmd string
}

func (d *CaddyDriver) configPath(clientName, app string) string {
	return filepath.Join(d.configDir, clientName+"--"+app+".conf")
}

func (d *CaddyDriver) WriteConfig(clientName string, app string, routes []Route) error {
	var lines []string
	lines = append(lines, fmt.Sprintf("# Auto-generated by opsen-agent for client: %s, app: %s", clientName, app))
	lines = append(lines, "# DO NOT EDIT")
	lines = append(lines, "")

	for _, route := range routes {
		for _, host := range route.Hosts {
			lines = append(lines, fmt.Sprintf("%s {", host))

			// Bind to specific address (for internal-only routes)
			if route.BindAddress != "" {
				lines = append(lines, fmt.Sprintf("  bind %s", route.BindAddress))
			}

			// Security headers
			lines = append(lines, "  header {")
			lines = append(lines, "    Strict-Transport-Security \"max-age=31536000; includeSubDomains\"")
			lines = append(lines, "    X-Content-Type-Options nosniff")
			lines = append(lines, "    X-Frame-Options DENY")
			lines = append(lines, "    Referrer-Policy strict-origin-when-cross-origin")
			lines = append(lines, "  }")

			// Custom headers
			for k, v := range route.Headers {
				lines = append(lines, fmt.Sprintf("  header %s \"%s\"", k, v))
			}

			// Rate limiting
			if route.RateLimitRps > 0 {
				lines = append(lines, fmt.Sprintf("  rate_limit {static %d %d}", route.RateLimitRps, route.RateLimitRps*2))
			}

			// CORS
			if route.CORS != nil && len(route.CORS.Origins) > 0 {
				lines = append(lines, "  @cors method OPTIONS")
				lines = append(lines, fmt.Sprintf("  header @cors Access-Control-Allow-Origin \"%s\"", strings.Join(route.CORS.Origins, ", ")))
				if len(route.CORS.Methods) > 0 {
					lines = append(lines, fmt.Sprintf("  header @cors Access-Control-Allow-Methods \"%s\"", strings.Join(route.CORS.Methods, ", ")))
				}
				lines = append(lines, "  header @cors Access-Control-Allow-Headers \"Content-Type, Authorization\"")
			}

			// Reverse proxy
			upstream := route.Upstream
			if route.PathPrefix != "" && route.PathPrefix != "/" {
				lines = append(lines, fmt.Sprintf("  handle_path %s* {", route.PathPrefix))
				lines = append(lines, fmt.Sprintf("    reverse_proxy %s", upstream))
				lines = append(lines, "  }")
			} else {
				lines = append(lines, fmt.Sprintf("  reverse_proxy %s", upstream))
			}

			lines = append(lines, "}")
			lines = append(lines, "")
		}
	}

	return os.WriteFile(d.configPath(clientName, app), []byte(strings.Join(lines, "\n")), 0644)
}

func (d *CaddyDriver) DeleteRoute(clientName string, app string, routeName string) error {
	return os.Remove(d.configPath(clientName, app))
}

func (d *CaddyDriver) DeleteApp(clientName string, app string) error {
	err := os.Remove(d.configPath(clientName, app))
	if os.IsNotExist(err) {
		return nil
	}
	return err
}

func (d *CaddyDriver) ListRoutes(clientName string, app string) ([]string, error) {
	return d.parseRoutes(d.configPath(clientName, app))
}

func (d *CaddyDriver) CountAllRoutes(clientName string) (int, error) {
	pattern := filepath.Join(d.configDir, clientName+"--*.conf")
	matches, err := filepath.Glob(pattern)
	if err != nil {
		return 0, err
	}

	total := 0
	for _, path := range matches {
		routes, err := d.parseRoutes(path)
		if err != nil {
			continue
		}
		total += len(routes)
	}
	return total, nil
}

func (d *CaddyDriver) parseRoutes(path string) ([]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return []string{}, nil
		}
		return nil, err
	}

	var routes []string
	for _, line := range strings.Split(string(data), "\n") {
		// Only match top-level blocks (not indented) — domain names start at column 0
		if len(line) > 0 && line[0] != ' ' && line[0] != '\t' && line[0] != '#' {
			trimmed := strings.TrimSpace(line)
			if strings.HasSuffix(trimmed, " {") {
				routes = append(routes, strings.TrimSuffix(trimmed, " {"))
			}
		}
	}
	return routes, nil
}

func (d *CaddyDriver) Reload() error {
	if d.reloadCmd == "" {
		return nil
	}

	parts := strings.Fields(d.reloadCmd)
	cmd := exec.Command(parts[0], parts[1:]...)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("reload failed: %s: %s", err, string(output))
	}
	return nil
}
