package ingress

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// TraefikDriver generates Traefik dynamic config files.
type TraefikDriver struct {
	configDir string
}

func (d *TraefikDriver) WriteConfig(clientName string, routes []Route) error {
	cfg := d.buildConfig(clientName, routes)

	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("marshaling traefik config: %w", err)
	}

	header := fmt.Sprintf("# Auto-generated by opsen-agent for client: %s\n# DO NOT EDIT\n", clientName)
	path := filepath.Join(d.configDir, clientName+".yml")

	return os.WriteFile(path, append([]byte(header), data...), 0644)
}

func (d *TraefikDriver) DeleteRoute(clientName string, routeName string) error {
	// For simplicity, we regenerate without the named route.
	// A production version might parse existing config and remove the route.
	// For now, deleting individual routes means removing the whole client config.
	path := filepath.Join(d.configDir, clientName+".yml")
	return os.Remove(path)
}

func (d *TraefikDriver) ListRoutes(clientName string) ([]string, error) {
	path := filepath.Join(d.configDir, clientName+".yml")
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return []string{}, nil
		}
		return nil, err
	}

	var cfg map[string]any
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, err
	}

	var routes []string
	if http, ok := cfg["http"].(map[string]any); ok {
		if routers, ok := http["routers"].(map[string]any); ok {
			for name := range routers {
				routes = append(routes, name)
			}
		}
	}
	return routes, nil
}

func (d *TraefikDriver) Reload() error {
	// Traefik watches the file provider directory — no reload needed
	return nil
}

func (d *TraefikDriver) buildConfig(clientName string, routes []Route) map[string]any {
	routers := map[string]any{}
	services := map[string]any{}
	middlewares := map[string]any{}

	// Platform security headers middleware (shared per client)
	headersMwName := clientName + "-security-headers"
	middlewares[headersMwName] = map[string]any{
		"headers": map[string]any{
			"stsSeconds":          31536000,
			"stsIncludeSubdomains": true,
			"contentTypeNosniff":  true,
			"frameDeny":           true,
			"referrerPolicy":     "strict-origin-when-cross-origin",
		},
	}

	for _, route := range routes {
		routerName := clientName + "-" + sanitize(route.Name)
		serviceName := routerName + "-svc"

		// Build rule
		var ruleParts []string
		if len(route.Hosts) > 0 {
			var hostRules []string
			for _, h := range route.Hosts {
				hostRules = append(hostRules, fmt.Sprintf("Host(`%s`)", h))
			}
			ruleParts = append(ruleParts, "("+strings.Join(hostRules, " || ")+")")
		}
		if route.PathPrefix != "" {
			ruleParts = append(ruleParts, fmt.Sprintf("PathPrefix(`%s`)", route.PathPrefix))
		}

		rule := strings.Join(ruleParts, " && ")

		// Router middlewares
		routerMiddlewares := []string{headersMwName}

		// Rate limiting
		if route.RateLimitRps > 0 {
			rlName := routerName + "-ratelimit"
			middlewares[rlName] = map[string]any{
				"rateLimit": map[string]any{
					"average": route.RateLimitRps,
					"burst":   route.RateLimitRps * 2,
				},
			}
			routerMiddlewares = append(routerMiddlewares, rlName)
		}

		// CORS
		if route.CORS != nil {
			corsName := routerName + "-cors"
			corsHeaders := map[string]any{}
			if len(route.CORS.Origins) > 0 {
				corsHeaders["accessControlAllowOriginList"] = route.CORS.Origins
			}
			if len(route.CORS.Methods) > 0 {
				corsHeaders["accessControlAllowMethods"] = route.CORS.Methods
			}
			corsHeaders["accessControlAllowHeaders"] = []string{"Content-Type", "Authorization"}
			corsHeaders["accessControlMaxAge"] = 86400
			middlewares[corsName] = map[string]any{
				"headers": corsHeaders,
			}
			routerMiddlewares = append(routerMiddlewares, corsName)
		}

		// Custom headers
		if len(route.Headers) > 0 {
			customName := routerName + "-custom-headers"
			middlewares[customName] = map[string]any{
				"headers": map[string]any{
					"customResponseHeaders": route.Headers,
				},
			}
			routerMiddlewares = append(routerMiddlewares, customName)
		}

		// Router
		router := map[string]any{
			"rule":        rule,
			"service":     serviceName,
			"entryPoints": []string{"websecure"},
			"middlewares":  routerMiddlewares,
		}

		if route.TLS != nil && route.TLS.ACME {
			router["tls"] = map[string]any{
				"certResolver": "letsencrypt",
			}
		}

		routers[routerName] = router

		// Service
		services[serviceName] = map[string]any{
			"loadBalancer": map[string]any{
				"servers": []map[string]string{
					{"url": "http://" + route.Upstream},
				},
			},
		}
	}

	return map[string]any{
		"http": map[string]any{
			"routers":     routers,
			"services":    services,
			"middlewares":  middlewares,
		},
	}
}

func sanitize(s string) string {
	return strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '-' {
			return r
		}
		return '-'
	}, s)
}
